// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalFinance.Infrastructure.Persistence;

#nullable disable

namespace PersonalFinance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PersonalFinanceDbContext))]
    partial class PersonalFinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalFinance.Domain.Finance.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DueDate")
                        .HasColumnType("integer")
                        .HasColumnName("due_day");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("LedgerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_ledger_id_name");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Domain.Finance.JournalEntries.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("LedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Domain.Finance.Ledgers.Ledger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id")
                        .HasName("pk_ledgers");

                    b.ToTable("ledgers", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Domain.Finance.JournalEntries.JournalEntry", b =>
                {
                    b.OwnsMany("PersonalFinance.Domain.Finance.JournalEntries.EntryLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("account_id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<Guid>("JournalEntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("journal_entry_id");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.HasKey("Id")
                                .HasName("pk_entry_lines");

                            b1.HasIndex("AccountId")
                                .HasDatabaseName("ix_entry_lines_account_id");

                            b1.HasIndex("JournalEntryId")
                                .HasDatabaseName("ix_entry_lines_journal_entry_id");

                            b1.ToTable("entry_lines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("JournalEntryId")
                                .HasConstraintName("fk_entry_lines_journal_entries_journal_entry_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("PersonalFinance.Domain.Finance.Ledgers.Ledger", b =>
                {
                    b.OwnsMany("PersonalFinance.Domain.Finance.Ledgers.LedgerMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.Property<Guid>("LedgerId")
                                .HasColumnType("uuid")
                                .HasColumnName("ledger_id");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("Id")
                                .HasName("pk_ledger_members");

                            b1.HasIndex("LedgerId", "UserId")
                                .IsUnique()
                                .HasDatabaseName("ix_ledger_members_ledger_id_user_id");

                            b1.ToTable("ledger_members", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("LedgerId")
                                .HasConstraintName("fk_ledger_members_ledgers_ledger_id");
                        });

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
